openapi: 3.0.3
info:
  title: Consent Artifact API Documentation
  description: 
    API documentation for managing Consent Artifacts
  version: 0.0.1
externalDocs:
  description: Find out more about Konnect
  url: https://github.com/Konnect-Agri


paths:
  /register:
    post:
      tags:
        - Consent artifact request from Consumer
      summary: Consent artifact request from Consumer
      description: Consent artifact request from Consumer
      operationId: register
      requestBody:
        description: Consent artifact request from Consumer
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ConsentArtifact'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
                            
components:
  schemas:
    RegisterResponse:
      description: The object returned as response on a consent artifact request
      type: object
      properties:
        caId:
          description: ID of the consent artifact in UUID format
          type: string
        consent_artifact:
          description: The actual consent artifact sent along side the request
          allOf:
            - $ref: '#/components/schemas/ConsentArtifact'
        user_id:
          description: user id of the consumer data is requested from
          type: string
        state:
          description: current state of the request
          type: string
        created_by:
          type: string
        webhook_url:
          description: Webhook URL where the user was notified of the access request
          
    ConsentArtifact:
      description: This schema defines the structure of a consent artifact. In the description of fields, the term `user` refers to the entity whose data needs to be accessed. For example in case of Safal Odisha, the `user` will be a farmer whose data needs to be fetched from the Krushak Odisha database.
      type: object
      properties:
        signature:
          description: Cryptographic signature to check the integrity of a consent artifact
          type: string
        created:
          description: Date on which the artifact was created
          type: string
        expires:
          description: Date on which the consent agreed for expires
          type: string
        id:
          description: UUID of the consent artifact
          type: string
        revocable:
          description: Defines if the credential is revocable or not
          type: boolean
        collector:
          description: Information about the data collector
          type: object
          properties:
            id: 
              type: string
            url:
              type: string
        consumer:
          description: Information about the data consumer (whoever will be using the data fetched using the consent artifact)
          type: object
          properties:
            id: 
              type: string
            url:
              type: string
        provider:
          description: Information about the data provider
          type: object
          properties:
            id: 
              type: string
            url:
              type: string
        revoker:
          description: Information about the artifact revoker
          type: object
          properties:
            id: 
              type: string
            url:
              type: string
        user:
          description: Information about the user whose data can be accessed via this consent artifact
          type: object
          properties:
            id: 
              type: string
        purpose:
          description: Purpose of the consent artifact
          type: string
        user_sign:
          description: crypotgraphic signature of the user whose data is to be accessed
          type: string
        collector_sign:
          description: cryptographic signature of the collector
          type: string
        frequency:
          description: This object represents the frequence with which the data can be accessed using this consent artifact. We can do `limit` number of requests within `ttl` number of seconds  
          type: object
          properties:
            ttl:
              type: number
            limit:
              type: number
        total_queries_allowed:
          description: Total data retrieval queries that can be made using this consent artifact in its lifetime, after these are exhausted the consent artifact cannot be used to send further requests even if it not revoked or expired.
          type: number
        log:
          description: A log of the access requests
          type: object
          properties:
            consent_use:
              type: object
              properties:
                url: 
                  type: string
            data_access:
              type: object
              properties:
                url: 
                  type: string
        data:
          description: This is the superset GraphQL query containing of all the fields that the user has granted access to.
          type: string